defaults:
  - sdg_text_davinci_003

data_dir: ${data_dir}/final_pre_computed/${.name}

filter_on_num_tokens: True
apply_ordering_heuristic: False # We will load a dataset that is already ordered
gzipped: True

dataset_parameters:
  test:
    dataset:
      load_dataset_params:
        split: "test_small_ordered"
